version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::058264074808:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-zPxyb0wzObCt"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::058264074808:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-KcFYNX4HkqKo"
cloudformation_execution_role = "arn:aws:iam::058264074808:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-NQ8eCe8Pbmm0"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-mv0ns9ti0z9h"
image_repository = ""
region = "ap-south-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::058264074808:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-2vKCzX8FI8E3"
cloudformation_execution_role = "arn:aws:iam::058264074808:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-JSIl02Dq4ObD"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-iqinqtpzock6"
image_repository = ""
region = "ap-south-1"
